# Generated by Django 2.2.1 on 2019-07-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='training',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='training',
            name='video',
        ),
        migrations.AddField(
            model_name='training',
            name='level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('medium', 'medium'), ('pro', 'pro')], default='medium', max_length=64),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('course', models.ManyToManyField(to='training.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('video', models.FileField(blank=True, null=True, upload_to='vids')),
                ('training', models.ManyToManyField(to='training.Training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='program',
            field=models.ManyToManyField(to='training.Program'),
        ),
    ]
